//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoZHosptalAutometion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string InvoiceType { get; set; }
        public string Status { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string DoctorName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> isProductDelivered { get; set; }
    }
}
