//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoZHosptalAutometion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSub
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string TotalinWord { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
