//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoZHosptalAutometion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSub
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> AddmissionDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string GuadianName { get; set; }
        public string GuardianMobile { get; set; }
    }
}
