//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtoZHosptalAutometion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportChecker
    {
        public int invoiceId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string PatientName { get; set; }
        public string Phone { get; set; }
        public string DoctorName { get; set; }
        public Nullable<bool> isProductDelivered { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Due { get; set; }
        public Nullable<decimal> Paid { get; set; }
    }
}
